services:
    mysql:
        container_name: mysqlglobal
        restart: always
        image: mysql:8.0.36
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: lazo
            MYSQL_PASSWORD: lazo
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/a.sql
            - ./maze.sql:/docker-entrypoint-initdb.d/b.sql
